### ISSUE TITLE
WakeWordEngine not compiling

### ISSUE THREAD

**Issue by swilson72** [alexa/alexa-avs-sample-app#272]
When I try to activate the WakeWordEngine in terminal window 3, I'm getting "bash: ./wakeWordAgent: No such file or directory".

I tried running . automated_install.sh again, and this appears in the output:

../ext/lib/libportaudio.a(pa_jack.o): In function `GetStreamTime':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference to `jack_frame_time'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference to `jack_get_sample_rate'
../ext/lib/libportaudio.a(pa_jack.o): In function `UpdateQueue':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1427: undefined reference to `jack_get_sample_rate'
../ext/lib/libportaudio.a(pa_jack.o): In function `JackCallback':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1562: undefined reference to `jack_port_get_buffer'
../ext/lib/libportaudio.a(pa_jack.o): In function `RealProcess':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1349: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1365: undefined reference to `jack_frame_time'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1367: undefined reference to `jack_port_get_latency'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1370: undefined reference to `jack_port_get_latency'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1391: undefined reference to `jack_port_get_buffer'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1402: undefined reference to `jack_port_get_buffer'
../ext/lib/libportaudio.a(pa_jack.o): In function `RealStop':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1688: undefined reference to `jack_port_connected'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1690: undefined reference to `jack_port_disconnect'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1696: undefined reference to `jack_port_connected'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1698: undefined reference to `jack_port_disconnect'
../ext/lib/libportaudio.a(pa_jack.o): In function `StartStream':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference to `jack_port_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference to `jack_port_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference to `jack_connect'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference to `jack_port_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference to `jack_port_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference to `jack_connect'
../ext/lib/libportaudio.a(pa_jack.o): In function `CleanUpStream':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:983: undefined reference to `jack_port_unregister'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:988: undefined reference to `jack_port_unregister'
../ext/lib/libportaudio.a(pa_jack.o): In function `OpenStream':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1080: undefined reference to `jack_port_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1081: undefined reference to `jack_client_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1087: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1181: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1214: undefined reference to `jack_port_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1215: undefined reference to `jack_port_register'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1224: undefined reference to `jack_port_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1225: undefined reference to `jack_port_register'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1241: undefined reference to `jack_get_ports'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1245: undefined reference to `jack_port_by_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1265: undefined reference to `jack_get_ports'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1269: undefined reference to `jack_port_by_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1301: undefined reference to `jack_port_get_latency'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1302: undefined reference to `jack_get_buffer_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1305: undefined reference to `jack_port_get_latency'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1306: undefined reference to `jack_get_buffer_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1310: undefined reference to `jack_frame_time'
../ext/lib/libportaudio.a(pa_jack.o): In function `Terminate':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:820: undefined reference to `jack_deactivate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:825: undefined reference to `jack_client_close'
../ext/lib/libportaudio.a(pa_jack.o): In function `IsFormatSupported':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference to `jack_get_sample_rate'
../ext/lib/libportaudio.a(pa_jack.o): In function `PaJack_Initialize':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:733: undefined reference to `jack_client_open'
../ext/lib/libportaudio.a(pa_jack.o): In function `BuildDeviceList':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:491: undefined reference to `jack_client_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:492: undefined reference to `jack_client_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:499: undefined reference to `jack_get_ports'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:517: undefined reference to `jack_client_name_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:558: undefined reference to `jack_get_sample_rate'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:589: undefined reference to `jack_get_ports'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:596: undefined reference to `jack_port_by_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:598: undefined reference to `jack_port_get_latency'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:610: undefined reference to `jack_get_ports'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:617: undefined reference to `jack_port_by_name'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:619: undefined reference to `jack_port_get_latency'
../ext/lib/libportaudio.a(pa_jack.o): In function `PaJack_Initialize':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:781: undefined reference to `jack_on_shutdown'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:782: undefined reference to `jack_set_error_function'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:783: undefined reference to `jack_get_buffer_size'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:785: undefined reference to `jack_set_sample_rate_callback'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:786: undefined reference to `jack_set_xrun_callback'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:800: undefined reference to `jack_client_close'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:787: undefined reference to `jack_set_process_callback'
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:788: undefined reference to `jack_activate'
../ext/lib/libportaudio.a(pa_jack.o): In function `PaJack_SetClientName':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1750: undefined reference to `jack_client_name_size'
../ext/lib/libportaudio.a(pa_jack.o): In function `PaJack_GetClientName':
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1765: undefined reference to `jack_get_client_name'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgentTest.dir/build.make:488: recipe for target 'wakeWordAgentTest' failed
make[2]: *** [wakeWordAgentTest] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
chown: changing ownership of ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/CMakeFiles/Progress/count.txt’: Operation not permitted
chown: changing ownership of ‘/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/CMakeFiles/Progress’: Operation not permitted

**Comment by swilso793** [comment]
Same problem

**Comment by gelvis** [comment]
Same

**Comment by ajotwani** [comment]
Just checking, did you cd into /src inside the wakeWordAgent directory?

`cd wakeWordAgent/src`

**Comment by swilso793** [comment]
Yes i run sudo make -j4 as in the makefile but it errors out on wakeWordAgent compiling. Something to do  with portaudio and jack.

**Comment by swilso793** [comment]
I compiled another version of portaudio with ./configure --without-jack and then moved the libportaudio.a from /usr/local/lib/ to alexa/samples/wakeword*/ext/lib. That removes alll the old errors but now i get: 
``CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o: In function `AlexaWakeWord::PortAudioWrapper::readData(std::vector<short, std::allocator<short> >*)':
PortAudioWrapper.cpp:(.text+0x210): undefined reference to `PaUtil_GetRingBufferReadAvailable'
PortAudioWrapper.cpp:(.text+0x25c): undefined reference to `PaUtil_ReadRingBuffer'
CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o: In function `AlexaWakeWord::PortAudioWrapper::paCallback(void const*, unsigned long)':
PortAudioWrapper.cpp:(.text+0x484): undefined reference to `PaUtil_WriteRingBuffer'
CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o: In function `AlexaWakeWord::PortAudioWrapper::init(int, int, int)':
PortAudioWrapper.cpp:(.text+0x680): undefined reference to `PaUtil_InitializeRingBuffer'
collect2: error: ld returned 1 exit status``

**Comment by abhisheksimion** [comment]
Same here

**Comment by MortalCornflake** [comment]
I have the same "bash: ./wakeWordAgent: No such file or directory" issue. definitely in the /src directory and all the .h and .cpp files are there but...

**Comment by tplaskota** [comment]
Had the same problem of "bash: ./wakeWordAgent: No such file or directory".

Looked around for a bit and turned out this program is built with cmake, which I didn't install on my raspberry yet, so i corrected that with `sudo apt-get install cmake`. Oh! It really wasn't there! So i guess it's no surprise that this didn't compile if automatic_installtion.sh didn't manage to make build objects.

So after cmake installation completed I buillt this myself (cmake 3.0.2, g++ 4.9), with calling `cmake .` (notice the dot) from `~/Desktop/aexa-avs-sample-app/samples/wakeWordAgent/src` and when this was done i finished with executing default make with `make`. It was successful and allowed me to `./wakeWordAgent`

All in all if someone stumbles here I'd recommend checking if cmake is already installed.

**Comment by kerryog** [comment]
This looks promising.  Can you give more details instructions?  I tried the 'sudo apt-get', but I'm still getting the same message

**Comment by swilso793** [comment]
That didn't work for me cause i had cmake already installed

**Comment by keleric** [comment]
It looks like it’s failing to build against a headphone jack module – lots of errors on the port audio jack. Are you running a clean/new copy of Raspbian? Which version of the Pi are you on?

**Comment by swilso793** [comment]
I uninstalled(purged) all packages that are needed to build snowboy and then i tried compiling again and it worked :)

**Comment by Skafte-Git** [comment]
Same problem.
I also think it has to do with cmake. Running "cmake ." in samples/wakeWordAgent/src/ gave me the error
Unknown CMake command "target_include_directories".
Which based on some googling is a function not introduced in cmake until version 2.8.12, whereas my version (from sudo apt-get install cmake on pi) is 2.8.9. Looking into compiling cmake myself gave me a bunch of pages on "cross-compiling" which I don't know what is and don't really want to get into. I am surprised this few people are having this issue if it is really due to the cmake version that comes standard from pi repository. Can anyone help?

**Comment by Skafte-Git** [comment]
Okay. Should mention I am running Jessie, not Wheezy, which may or may not explain my issues.
Due to cmake version 2.8.9 I circumvented target_include_directories by replacing
`target_include_directories( wakeWordAgent PRIVATE ${CMAKE_SOURCE_DIR}/../ext/include `
with
```
set_property(TARGET wakeWordAgent
                PROPERTY INCLUDE_DIRECTORIES ${CMAKE_SOURCE_DIR}/../ext/include)
```
Now cmake . works! Then I found out GCC and G++ is only version 4.6 on the Pi, so installed required versions and symlinked:
```
sudo rm /usr/bin/gcc
sudo rm /usr/bin/g++
sudo apt-get install gcc-4.7 g++-4.7
sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc
sudo ln -s /usr/bin/g++-4.7 /usr/bin/g++
```

You can check with gcc -v and g++ -v. 
But I still get errors from make -j4:

[ 30%] [ 30%] [ 30%] [ 30%] Building CXX object CMakeFiles/wakeWordAgent.dir/main.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordIPCFactory.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordIPCFactory.cpp:16:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordIPCSocket.h:32:11: error: looser throw specifier for ‘virtual AlexaWakeWord::WakeWordIPCSocket::~WakeWordIPCSocket()’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordIPCFactory.h:17:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordIPCFactory.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordIPC.h:26:11: error:   overriding ‘virtual AlexaWakeWord::WakeWordIPC::~WakeWordIPC() noexcept (true)’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp:14:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.h:44:3: error: looser throw specifier for ‘virtual AlexaWakeWord::WakeWordAgent::~WakeWordAgent()’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngine.h:17:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.h:17,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.h:19,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordDetectedInterface.h:22:11: error:   overriding ‘virtual AlexaWakeWord::WakeWordDetectedInterface::~WakeWordDetectedInterface() noexcept (true)’
CMakeFiles/wakeWordAgent.dir/build.make:146: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordIPCFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordIPCFactory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/main.cpp:23:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.h:44:3: error: looser throw specifier for ‘virtual AlexaWakeWord::WakeWordAgent::~WakeWordAgent()’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngine.h:17:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.h:17,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordAgent.h:19,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/main.cpp:23:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordDetectedInterface.h:22:11: error:   overriding ‘virtual AlexaWakeWord::WakeWordDetectedInterface::~WakeWordDetectedInterface() noexcept (true)’
CMakeFiles/wakeWordAgent.dir/build.make:77: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordAgent.cpp.o] Error 1
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:39:3: error: looser throw specifier for ‘virtual AlexaWakeWord::KittAiSnowboyWakeWordEngine::~KittAiSnowboyWakeWordEngine()’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.h:17:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngine.h:28:11: error:   overriding ‘virtual AlexaWakeWord::WakeWordEngine::~WakeWordEngine() noexcept (true)’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:18:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/SensoryWakeWordEngine.h:30:3: error: looser throw specifier for ‘virtual AlexaWakeWord::SensoryWakeWordEngine::~SensoryWakeWordEngine()’
In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.h:17:0,
                 from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:14:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngine.h:28:11: error:   overriding ‘virtual AlexaWakeWord::WakeWordEngine::~WakeWordEngine() noexcept (true)’
CMakeFiles/wakeWordAgent.dir/build.make:54: recipe for target 'CMakeFiles/wakeWordAgent.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/main.cpp.o] Error 1
CMakeFiles/wakeWordAgent.dir/build.make:100: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2

Anyone who knows c++ that can tell whats wrong now?

**Comment by joelplambeck** [comment]
@swilso793 how exactly did you do that? with the code

`sudo apt-get purge snowboy`

i always get the error: Unable to locate package snowboy. I'm fairly new to this detailed explanation would be appreciated.

My alexa works but just the wakeWordAgent wont launch... (no such file or directory) installed it twice and cmake is installed...

Thank you very much for your help

**Comment by vichou** [comment]
Any news here? I'm also unable to compile ..

```
Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
[ 13%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 20%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 26%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 33%] Linking CXX executable wakeWordAgent
../ext/lib/libportaudio.a(pa_jack.o): In function `GetStreamTime':
/home/vic/tmp/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference to `jack_frame_time'
/home/vic/tmp/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference to `jack_get_sample_rate'
../ext/lib/libportaudio.a(pa_jack.o): In function `UpdateQueue':
/home/vic/tmp/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++/portaudio/src/hostapi/jack/pa_jack.c:1427: undefined reference to `jack_get_sample_rate'
../ext/lib/libportaudio.a(pa_jack.o): In function `JackCallback':
```

**Comment by Alexnagel** [comment]
@spacerIV Looks like the jack dependency isn't there, check #418 maybe that helps

**Comment by spacerIV** [comment]
^^ TYVM ^^
